on join:
  wait 2 seconds
  message ""
  message "&fⓎ <##FCC72D>&lWelcome To Survival!"
  message ""
  message " &8• &7Use &c/rewards &7to claim your rewards!"
  message " &8• &7Use &6/vote &7to obtain daily rewards!"
  message " &8• &7Use &b/discord &7to join our discord community!"
  message ""
  message "    け <##FCC72D><link:INSERT_LINK_HERE_WITH_HTTPS>store.survival.com &fけ"
  message ""